# Site
repository: tothlp/tothlp.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

last_update: &last_update 2023.03.19.

# Personal info
name: &author T√≥th L√°szl√≥
title: Full-Stack Developer
email: hello@tothlp.hu
email_title: <i class="far fa-envelope"></i>
phone: Budapest
phone_title: <i class="far fa-home"></i>
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: tothlp
github_username:  tothlp
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: tothlp
linkedin_username: tothlp
#xbox_username: tothlp
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/tothlp
- title: Notes
  icon: fas fa-sticky-note
  url: https://tothlp.hu/garden

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-WHNXZE6LBQ"
# google_analytics: "UA-00000000-0"

# About Section
about_title: R√≥lam
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Szia! *T√≥th L√°szl√≥* vagyok, Full-Stack szoftverfejleszt≈ë. Jelenleg f≈ëleg ![Kotlin](https://img.shields.io/badge/-Kotlin-black?logo=kotlin), ![Java](https://img.shields.io/badge/-Java-FFFFFF?logo=openjdk&logoColor=black) √©s ![Typescript](https://img.shields.io/badge/-Typescript-3178C6?logo=typescript&logoColor=white) nyelveken fejlesztek.

  L√°t√°sm√≥dom szerint a szoftverfejleszt√©s komoly alkot√≥i munka, amellyel √©rt√©ket lehet l√©trehozni.
  Munk√°m sor√°n fontos sz√°momra, hogy olyan megold√°sokat fejlesszek, amelyek min√©l jobban megk√∂nny√≠tik az √ºgyfelek munkav√©gz√©s√©t.
  Szeretem t√∂bb szemsz√∂gb≈ël l√°tni az alkalmaz√°sokat, √≠gy egyr√©szt
  l√©nyegesnek tartom a probl√©m√°k √ºgyf√©lk√∂zpont√∫ megk√∂zel√≠t√©s√©t, m√°sr√©szt --ha lehet≈ës√©gem van r√°-- szeretek n√©mik√©pp r√°l√°tni a szoftver √ºzemeltet√©s√©re is.
  Nyitott vagyok az √∫j technol√≥gi√°k megismer√©s√©re. Nem z√°rk√≥zom el √∫j *ter√ºletek* megismer√©s√©t≈ël sem, de nem titkolt c√©lom, hogy eddigi tud√°somat is
  szeretn√©m min√©l jobban elm√©ly√≠teni.

content:
  - title: <small><i class="fas fa-tools"></i> </small>  Skills   <small><i class="fas fa-feather"></i></small>
    layout: text
    content: |
      ## Nyelvek

      ![Kotlin](https://img.shields.io/badge/-Kotlin-444?logo=kotlin&style=for-the-badge) ![Java](https://img.shields.io/badge/-Java-FFFFFF?logo=openjdk&logoColor=black&style=for-the-badge) ![Typescript](https://img.shields.io/badge/-Typescript-3178C6?logo=typescript&logoColor=white&style=for-the-badge) ![HTML](https://img.shields.io/badge/-HTML5-E34F26?logo=html5&logoColor=white&style=for-the-badge) ![CSS3](https://img.shields.io/badge/-CSS3-1572b6?logo=css3&style=for-the-badge) 
      ![Ruby](https://img.shields.io/badge/-Ruby-cc342d?style=for-the-badge&logo=ruby) 
      ![Latex](https://img.shields.io/badge/-Latex-008080?style=for-the-badge&logo=latex) ![Wolfram](https://img.shields.io/badge/-Wolfram-DD1100?style=for-the-badge&logo=wolfram) ![Markdown](https://img.shields.io/badge/-Markdown-444?style=for-the-badge&logo=markdown) 

      ## Keretrendszerek

      ![SpringBoot](https://img.shields.io/badge/-SpringBoot-6DB33F?style=for-the-badge&logo=springboot&logoColor=white) ![Angular](https://img.shields.io/badge/-Angular-DD0031?style=for-the-badge&logo=angular) 
      ![Ruby on Rails](https://img.shields.io/badge/-Ruby%20on%20Rails-CC0000?style=for-the-badge&logo=rubyonrails) 
      ![NestJS](https://img.shields.io/badge/-NestJS-E0234E?style=for-the-badge&logoColor=white&logo=nestjs) 
      ![Jekyll](https://img.shields.io/badge/-Jekyll-CC0000?style=for-the-badge&logoColor=white&logo=jekyll) 
      ![Bootstrap](https://img.shields.io/badge/-Bootstrap-7952B3?style=for-the-badge&logo=bootstrap&logoColor=white)
      ![Laravel](https://img.shields.io/badge/-Laravel-FF2D20?style=for-the-badge&logo=laravel&logoColor=white) 

      ## Adatb√°zisok

      ![MySQL](https://img.shields.io/badge/-MySQL-4479A1?style=for-the-badge&logo=mysql&logoColor=white) 
      ![Oracle](https://img.shields.io/badge/-Oracle-F80000?style=for-the-badge&logo=oracle&logoColor=white) 

      ## Verzi√≥kezel√©s

      ![Git](https://img.shields.io/badge/-Git-F05032?style=for-the-badge&logo=git&logoColor=white)
      ![GitHub](https://img.shields.io/badge/-GitHub-181717?style=for-the-badge&logo=github&logoColor=white)
      ![GitLab](https://img.shields.io/badge/-GitLab-FC6D26?style=for-the-badge&logo=gitlab&logoColor=white)

      ## OS
      
      ![macOS](https://img.shields.io/badge/-macOS-black?style=for-the-badge&logo=macos&logoColor=white)
      ![Linux](https://img.shields.io/badge/-Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black)
      ![Windows](https://img.shields.io/badge/-Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white)
      
      ## Hosting / CI/CD

      ![Heroku](https://img.shields.io/badge/-Heroku-430098?style=for-the-badge&logo=heroku&logoColor=white)
      ![GitLab Pipelines](https://img.shields.io/badge/-GitLab%20Pipelines-FC6D26?style=for-the-badge&logo=gitlab&logoColor=white)
      ![GitHub Pages](https://img.shields.io/badge/-GitHub%20Pages-black?style=for-the-badge&logo=githubpages&logoColor=white)
      ![Jenkins](https://img.shields.io/badge/-Jenkins-D24939?style=for-the-badge&logoColor=white&logo=jenkins)

      ## K√∂rnyezetkezel√©s
      ![Docker](https://img.shields.io/badge/-Docker-2496ED?style=for-the-badge&logoColor=white&logo=docker)
      ![Vagrant](https://img.shields.io/badge/-Vagrant-1868F2?style=for-the-badge&logoColor=white&logo=vagrant)

      ## Build / F√ºgg≈ës√©gkezel√©s

      ![Gradle](https://img.shields.io/badge/-Gradle-02303A?style=for-the-badge&logoColor=white&logo=gradle)
      ![Yarn](https://img.shields.io/badge/-Yarn-2C8EBB?style=for-the-badge&logoColor=white&logo=yarn)

      ## App / Egy√©b

      ![Bash](https://img.shields.io/badge/-Bash-4EAA25?style=for-the-badge&logoColor=white&logo=gnubash) 
      ![VSCode](https://img.shields.io/badge/-VSCode-007ACC?style=for-the-badge&logoColor=white&logo=visualstudiocode)
      ![Windows Terminal](https://img.shields.io/badge/-Windows%20Terminal-4D4D4D?style=for-the-badge&logoColor=white&logo=windowsterminal)
      ![IntelliJ IDEA](https://img.shields.io/badge/-IDEA-000000?style=for-the-badge&logoColor=white&logo=intellijidea)


  - title: Projektek # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Landing
        link: https://tothlp.hu
        #link_text: Link Text
        description: |
          Szerettem volna egy helyet, ahol el√©rhet≈ës√©gekkel egy√ºtt √∂ssze van szedve p√°r inf√≥ r√≥lam. Az oldal motorh√°zteteje alatt a ![Jekyll](https://img.shields.io/badge/-Jekyll-CC0000?logoColor=white&logo=jekyll) d√ºb√∂r√∂g, √©s a ![GitHub Pages](https://img.shields.io/badge/-GitHub%20Pages-black?logo=githubpages&logoColor=white) szolg√°lja ki.
      # - layout: left 
      #   title: Blog / Landing
      #   link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #   link_text: Link Text
        additional_links:
          - title:  Github repo
            icon: fab fa-github
            url: https://github.com/tothlp/tothlp.github.io
      #     - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #       icon: fab fa-github
      #       url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #   quote: >
      #     Short overview of the project (optional)
      #   description: | # this will include new lines to allow paragraphs
      #     Description about the work on/with the project
      - layout: left
        title: Digital Garden
        link: https://tothlp.hu/garden
        # link_text: Link Text
        description: |
          Work in progress...
      # - layout: left 
      #   title: Blog / Landing
      #   link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #   link_text: Link Text
        additional_links:
          - title:  Github repo
            icon: fab fa-github
            url: https://github.com/tothlp/garden
      #     - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #       icon: fab fa-github
      #       url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #   quote: >
      #     Short overview of the project (optional)
      #   description: | # this will include new lines to allow paragraphs
      #     Description about the work on/with the project
  - title: Tapasztalat
    layout: list
    content:
      - layout: right
        title: R√©gens Zrt.
        sub_title: Full-Stack Developer
        caption: 2017 j√∫lius - jelenleg
        link: www.regens.com
        description: | # this will include new lines to allow paragraphs
          A R√©gensn√©l, mint Backend fejleszt≈ë gyakornok kezdtem el dolgozni. Akkoriban feladataim a backend-fejleszt√©s alapjainak elsaj√°t√≠t√°sa k√∂r√© √©p√ºltek. Itt f≈ëleg
          a Spring Boot keretrendszer saj√°toss√°gaival ismerkedtem meg, viszont m√°sodlagos skillsetk√©nt igyekeztem ismereteket szerezni a CI/CD alapjaib√≥l.

          A gyakornoki id≈ëm letelt√©vel fokozatosan beletanultam a Frontend fejleszt√©sbe is. Sz√°mos projekten dolgoztam, azonban f≈ëleg a p√©nz√ºgyi alkalmaz√°saink fejleszt√©s√©ben vettem r√©szt.
          Itt lehet≈ës√©gem ny√≠lt t√∂bb alkalmaz√°sb√≥l √°ll√≥ komplexebb rendszerek, valamint a sz√°ml√°z√°si folyamatok megismer√©s√©re.
      - layout: left
        title: SZTE EH√ñK
        sub_title: Web Developer
        caption: 2016 - 2017
        description: | # this will include new lines to allow paragraphs
            Egy szakmai k√∂z√∂ss√©g tagjak√©nt a SZTE Hallgat√≥i √∂nkorm√°nyzatok weboldalainak fejleszt√©s√©ben vettem r√©szt, ahol ![PHP](https://img.shields.io/badge/-PHP-777BB4?logoColor=white&logo=php) √©s ![Laravel](https://img.shields.io/badge/-Laravel-FF2D20?logo=laravel&logoColor=white) haszn√°lat√°ban szereztem ismereteket.
  - title: Tanulm√°nyok
    layout: list
    content:
      - layout: top-right
        title: Szegedi Tudom√°nyegyetem
        sub_title: Programtervez≈ë informatikus BSc
        caption: 2019
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
  - title: √ñnk√©ntess√©g
    layout: list
    content:
      - layout: left
        title: S√≠k S√°ndor Piarista Egyetemi Szakkoll√©gium
        sub_title: Di√°kbizotts√°gi tag
        caption: 2014 - 2018
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
            - R√©szv√©tel a koll√©gium programjainak szervez√©s√©ben √©s lebonyol√≠t√°s√°ban
            - A bels≈ë √©s k√ºls≈ë kommunik√°ci√≥s csatorn√°k m≈±k√∂dtet√©se
            - Az informatikai h√°tt√©r karbantart√°sa
            - K√∂z√∂ss√©gi feladatok koordin√°l√°sa
            - Seg√≠ts√©g az adminisztr√°ci√≥s feladatokban
  - title: Egy kicsit t√∂bb inf√≥ r√≥lam
    layout: text
    content: | # this will include new lines to allow paragraphs
      > "Az ember nagy dolgokat vitt m√°r v√©gbe, de nem az√©rt, mert annyira okos, hanem mert van keze, √©s tud k√°v√©t f≈ëzni." <br/><br/>
      > /Flash Rosenberg/

      Szeretek Tech cikkeket olvasni, illetve n√©hanapj√°n egy-k√©t kedvenc appom changelogj√°t. ü§ì Ha nem cikkeket olvasok, akkor f≈ëleg fantasy √©s YA reg√©nyeket.
      Sok angol kifejez√©st haszn√°lok a mindennapi besz√©demben. Szeretek f≈ëzni. üë®‚Äçüç≥ Sosem voltam √∂r√∂kmozg√≥, de szeretek j√≥g√°zni √©s biciklizni. 
      Az erdei √©s hegyi t√∫r√°k alatt √©rzem √∫gy igaz√°n, hogy t√∂lt≈ën vagyok. üèûÔ∏è üå≤ K√°v√©f√ºgg≈ë vagyok. ‚òïÔ∏è Szeretem a vil√°gos p√∂rk√∂l√©s≈± k√°v√©t, √©s az alternat√≠v elk√©sz√≠t√©si m√≥dokat. Szabadid≈ëmben n√©ha vide√≥j√°t√©kokat ny√∂sztetek, szigor√∫an konzolon. üéÆ
  - title: Gear
    layout: list
    content:
      - layout: left
        # border: weak // or no value.
        title: K√°v√© <i class="fas fa-coffee"></i>
        sub_title: Mivel f≈ëz√∂k reggel
        description: |
          * **Brewer:** Aeropress / Nanopresso / Prismo / Bialetti Moka Express
          * **Scale:** Timemore Black Mirror Basic
          * **Grinder:** 1Zpresso JX
          * **Kettle:** Tchibo (98096) elektromos hatty√∫nyak√∫ v√≠zforral√≥
      - layout: right
        title: <i class="fas fa-microchip"></i> Hardverek
        sub_title: Mivel dolgozom ut√°na
        description: |
          * <i class="fas fa-desktop"></i> Mac mini 2018 (i3 3,6 GHz, 8GB)
          * <i class="fas fa-headphones"></i> Sony WH-1000XM3 / Apple AirPods 3
  - title: Kapcsolat
    layout: text
    content: |
      Az oldal tetej√©n megtal√°lhat√≥ sz√°mos el√©rhet≈ës√©gem. Az emaileket naponta n√©zem, √≠rj b√°tran!
      √úzenetk√ºld≈ëk tekintet√©ben prefer√°lom a titkos√≠tott szolg√°ltat√°sokat, f≈ëleg ![Telegram](https://img.shields.io/badge/-Telegram-26A5E4?logoColor=white&logo=telegram)-ot haszn√°lok.
# Footer
footer_show_references: true
references_title: *last_update

# Build settings
#theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "tothlp.github.io.code-workspace"
  ]
